from settings import *
from entities import *
class Boss(Mob):
    def __init__(self,num):
        if(num==1):
            self.leader=10
            self.hp=30
            self.str=10
            self.dex=6
            self.int=10
            self.AC=10
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=5
            self.shout=100
            self.icon=Boss_icon
            self.name='World Ender'
            self.inventory=[]
            self.wear=Armor(3,Armor_icon,'leather armor',2)
            self.wield=Weapon(5,0,3,Weapon_icon,'Excalibolg',3,3,3,3)
            self.DV=1
            self.shield=self.wield
            self.ER=self.shield.ER+self.wear.ER
            self.MR=self.shield.MR
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=5000
            self.drop=[Weapon(5,0,3,Weapon_icon,'Excalibolg',3,3,3,3)]
            self.doping=['huge']
            self.status=Status_template.copy()
            self.catchphrase=('Despair overwhelms '+name+'.','Despair overwhelms '+name+'.')
        elif(num==2):
            self.leader=10
            self.hp=20
            self.str=12
            self.dex=30
            self.int=6
            self.AC=8
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=0
            self.shout=0
            self.icon=Boss_icon
            self.name='Midorime'
            self.inventory=[]
            self.wear=Armor(3,Armor_icon,'leather armor',2)
            self.wield=Weapon(1,6,0,Weapon_icon,'Satosame',1,0,0,0,['death'])
            self.DV=1
            self.shield=Weapon(0,0,0,Shield_icon,'',2)
            self.ER=self.wear.ER
            self.MR=0
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=50000
            self.drop=[Weapon(1,6,0,Weapon_icon,'Satosame',1,0,0,0,['death'])]
            self.doping=['stealth','death']
            self.status=Status_template.copy()
            self.catchphrase=(name+' senses murderous aura.',name+' senses murderous aura.')
        elif(num==3):
            self.leader=10
            self.hp=30
            self.str=24
            self.dex=30
            self.int=12
            self.AC=12
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=6
            self.shout=100
            self.icon=Boss_icon
            self.name='Kill-Shot'
            self.inventory=[]
            self.wear=Armor(1,Armor_icon,'robe',0)
            self.wield=Weapon(6,6,2,Weapon_icon,'Shinzowatari',3,6,2,4,['purify'])
            self.DV=1
            self.shield=self.wield
            self.ER=self.wear.ER+self.shield.ER
            self.MR=self.shield.MR+2
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=1000000
            self.drop=[Weapon(6,6,2,Weapon_icon,'Shinzowatari',3,6,2,4,['purify'])]
            self.doping=['purify','kai','vampirism']
            self.status=Status_template.copy()
            self.catchphrase=(name+' senses '+name+"'s life force being drained.",name+' senses '+name+"'s life force being drained.")
        elif(num==4):
            self.leader=10
            self.hp=60
            self.str=30
            self.dex=30
            self.int=30
            self.AC=12
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=4
            self.shout=100
            self.icon=Boss_icon
            self.name='Shounin Bat'
            self.inventory=[]
            self.wear=Armor(3,Armor_icon,'leather armor',2)
            self.wield=Weapon(4,4,2,Weapon_icon,'Silver Bat',1,0,0,0,['illusion'])
            self.DV=1
            self.shield=Weapon(0,0,0,Shield_icon,'',2)
            self.ER=self.wear.ER
            self.MR=4+self.shield.MR
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=5000000
            self.drop=[Weapon(4,4,2,Weapon_icon,'Silver Bat',1,0,0,0,['illusion'])]
            self.doping=['illusion','roller-skates','kai']
            self.status=Status_template.copy()
            self.catchphrase=(name+' shivers as '+name+' hears sound of inline skates.',name+' shivers as '+name+' hears sound of inline skates.')
        elif(num==5):
            self.leader=10
            self.hp=100
            self.str=12
            self.dex=12
            self.int=12
            self.AC=24
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=5
            self.shout=100
            self.icon=Boss_icon
            self.name='Dwarf Rabbit'
            self.inventory=[]
            self.wear=Armor(12,Armor_icon,'pearl shellmail',0,['purify'])
            self.wield=Weapon(8,1,4,Weapon_icon,'pearl cudgel',3,8,1,4,['parry'])
            self.DV=1
            self.shield=self.wield
            self.ER=self.wear.ER+self.shield.ER
            self.MR=8+self.shield.MR
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=10**9
            self.drop=[Weapon(8,1,4,Weapon_icon,'pearl cudgel',3,8,1,4,['purify']),Armor(12,Armor_icon,'pearl shellmail',0,['purify'])]
            self.doping=['purify','parry','rabbit','huge']
            self.status=Status_template.copy()
            self.catchphrase=('Dwarf Rabbit shouts prayers!',name+' hears prayers.')
        elif(num==6):
            self.leader=10
            self.hp=666
            self.str=12
            self.dex=12
            self.int=12
            self.AC=666
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=0
            self.shout=100
            self.icon=Boss_icon
            self.name='Lucifer'
            self.inventory=[]
            self.wear=Armor(12,Armor_icon,'ebony platemail',0,['vampirism'])
            self.wield=Weapon(6,6,6,Weapon_icon,'ebony sword',1,0,0,0,['vampirism'])
            self.DV=0
            self.shield=Weapon(6,0,6,Shield_icon,'ebony shield',2,0,0,0,['vampirism'])
            self.ER=self.wear.ER+self.shield.ER
            self.MR=666
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.Bstr=12
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=10**8
            self.drop=[Weapon(3,3,3,Weapon_icon,'ebony sword',1,0,0,0,['vampirism']),Armor(12,Armor_icon,'ebony platemail',0,['vampirism'])]
            self.doping=['vampirism','kai','pride']
            self.status=Status_template.copy()
            self.catchphrase=('Lucifer laughs haughtily noticing '+name+'.',name+' hears a haughty laugh.')
        elif(num==7):
            self.leader=10
            self.hp=60
            self.str=1
            self.dex=1
            self.int=60
            self.AC=18
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=1
            self.shout=100
            self.icon=Boss_icon
            self.name='Belphegor'
            self.inventory=[Item('?',1,'magic potion')]*8
            self.wear=Armor(6,Armor_icon,'ebony scalemail',0,['vampirism'])
            self.wield=Weapon(1,0,6,Weapon_icon,'ebony wand',1,0,0,0,['illusion','vampirism'])
            self.DV=0
            self.shield=Weapon(6,0,6,Shield_icon,'ebony shield',2,0,0,0,['vampirism'])
            self.ER=self.wear.ER+self.shield.ER
            self.MR=4+self.shield.MR
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=10**8
            self.drop=[Weapon(1,0,6,Weapon_icon,'ebony wand',1,0,0,0,['illusion']),Armor(6,Armor_icon,'ebony scalemail',0,['vampirism'])]
            self.doping=['illusion','vampirism','kai','sloth']
            self.status=Status_template.copy()
            self.catchphrase=('Belphegor yawns meeting '+name+"'s gaze.",name+' hears a yawn.')
        elif(num==8):
            self.leader=10
            self.hp=60
            self.str=10
            self.dex=20
            self.int=30
            self.AC=15
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=1
            self.shout=100
            self.icon=Boss_icon
            self.name='Mammon'
            self.inventory=[Item('?',5,'brilliance potion')]*8
            self.wear=Armor(4,Armor_icon,'golden scalemail',3)
            self.wield=Weapon(1,2,3,Weapon_icon,'golden wand',3,6,0,12,['teleport'])
            self.DV=1
            self.shield=self.wield
            self.ER=self.wear.ER+self.shield.ER
            self.MR=4+self.shield.MR
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=10**8
            self.drop=[Weapon(1,2,3,Weapon_icon,'golden wand',3,6,0,12,['teleport']),Armor(4,Armor_icon,'golden scalemail',3)]
            self.doping=['vampirism','kai','greed','teleport']
            self.status=Status_template.copy()
            self.catchphrase=('Mammon smiles while scanning '+name+"'s backpack.",name+' feels uncomfortable.')
        elif(num==9):
            self.leader=10
            self.hp=60
            self.str=12
            self.dex=24
            self.int=1
            self.AC=18
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=4
            self.shout=100
            self.icon=Boss_icon
            self.name='Satan'
            self.inventory=[Item('?',6,'madness potion')]*8
            self.wear=Armor(6,Armor_icon,'ebony scalemail',0,['vampirism'])
            self.wield=Weapon(8,2,2,Weapon_icon,'ebony cudgel',3,6,6,6,['vampirism'])
            self.DV=1
            self.shield=self.wield
            self.ER=self.wear.ER+self.shield.ER
            self.MR=4+self.shield.MR
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.Bstr=self.str
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=10**8
            self.drop=[Weapon(8,2,2,Weapon_icon,'ebony cudgel',3,6,6,6,['vampirism']),Armor(6,Armor_icon,'ebony scalemail',0,['vampirism'])]
            self.doping=['vampirism','kai','wrath','huge']
            self.status=Status_template.copy()
            self.catchphrase=('Satan screams in fury!',name+' hears a furious scream!')
        elif(num==10):
            self.leader=10
            self.hp=60
            self.str=20
            self.dex=20
            self.int=20
            self.AC=6
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=0
            self.shout=100
            self.icon=Boss_icon
            self.name='Leviatan'
            self.inventory=[Item('?',2,'poison potion')]*8
            self.wear=Armor(0,Armor_icon,'shabby rags',0,['vampirism'])
            self.wield=Weapon(1,1,1,Weapon_icon,'shabby dagger',1,0,0,0,['vampirism'])
            self.DV=1
            self.shield=Weapon(0,0,0,Shield_icon,'',2)
            self.ER=self.wear.ER+self.shield.ER
            self.MR=4+self.shield.MR
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=10**8
            self.Aenvy=0
            self.Denvy=0
            self.drop=[Weapon(1,1,1,Weapon_icon,'shabby dagger',1,0,0,0,['vampirism']),Armor(0,Armor_icon,'shabby rags',0,['vampirism'])]
            self.doping=['vampirism','kai','envy']
            self.status=Status_template.copy()
            self.catchphrase=('Leviatan stares intently at '+name+"'s belongings.",name+' feels an intent stare.')
        elif(num==11):
            self.leader=10
            self.hp=60
            self.str=40
            self.dex=20
            self.int=1
            self.AC=8
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=0
            self.shout=1
            self.icon=Boss_icon
            self.name='Beelzebub'
            self.inventory=[Item('?',0,'regeneration potion')]*8
            self.wear=Armor(2,Armor_icon,'ebony hide',-1,['vampirism'])
            self.wield=Weapon(1,1,1,Weapon_icon,'')
            self.DV=1
            self.shield=Weapon(0,0,0,Shield_icon,'',2)
            self.ER=self.wear.ER+self.shield.ER
            self.MR=4+self.shield.MR
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=10**8
            self.drop=[Armor(2,Armor_icon,'ebony hide',-1,['vampirism'])]
            self.doping=['vampirism','kai','gluttony','huge']
            self.status=Status_template.copy()
            self.catchphrase=("Saliva oozes from Beelzebub's mouth, ears and eyes.",name+' hears some liquid dropping on the floor.')
        elif(num==12):
            self.leader=10
            self.hp=60
            self.str=24
            self.dex=12
            self.int=1
            self.AC=8
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=0
            self.shout=100
            self.icon=Boss_icon
            self.name='Asmodeus'
            self.inventory=[Item('?',0,'healing potion')]*8
            self.wear=Armor(2,Armor_icon,'ebony hide',-1,['vampirism'])
            self.wield=Weapon(3,3,4,Weapon_icon,'ebony dagger',1,0,0,0,['vampirism'])
            self.DV=1
            self.shield=Weapon(0,0,0,Shield_icon,'',2)
            self.ER=self.wear.ER+self.shield.ER
            self.MR=4+self.shield.MR
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=10**8
            self.drop=[Armor(2,Armor_icon,'ebony hide',-1,['vampirism']),Weapon(3,3,4,Weapon_icon,'ebony dagger',1,0,0,0,['vampirism'])]
            self.doping=['vampirism','kai','lust']
            self.status=Status_template.copy()
            self.catchphrase=("Asmodeus's bloodshot eyes roll in "+name+"'s direction.",name+' hears a rolling sound.')
