from settings import *
from entities import *
Weapon_types_list=Weapon_types_list+('Excalibolg','Satosame','Shinzowatari','Silver Bat')
class Boss(Mob):
    def __init__(self,num):
        if(num==1):
            self.leader=10
            self.hp=30
            self.str=10
            self.dex=6
            self.int=10
            self.AC=10
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=9
            self.shout=100
            self.icon=Boss_icon
            self.name='World Ender'
            self.inventory=[]
            self.wear=Armor(3,Armor_icon,'leather armor',2)
            self.wield=Weapon(5,0,3,Weapon_icon,'Excalibolg',3,3,3,3)
            self.DV=1
            self.shield=self.wield
            self.ER=self.shield.ER+self.wear.ER
            self.MR=self.shield.MR
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=5000
            self.drop=[Weapon(5,0,3,Weapon_icon,'Excalibolg',3,3,3,3)]
            self.doping=[]
            self.catchphrase=('Despair overwhelms '+name+'.','Despair overwhelms '+name+'.')
        elif(num==2):
            self.leader=10
            self.hp=20
            self.str=12
            self.dex=30
            self.int=6
            self.AC=8
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=0
            self.shout=0
            self.icon=Boss_icon
            self.name='Midorime'
            self.inventory=[]
            self.wear=Armor(3,Armor_icon,'leather armor',2)
            self.wield=Weapon(1,6,0,Weapon_icon,'Satosame',1,0,0,0,['death'])
            self.DV=1
            self.shield=Weapon(0,0,0,Shield_icon,'',2)
            self.ER=self.wear.ER
            self.MR=0
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=50000
            self.drop=[Weapon(1,6,0,Weapon_icon,'Satosame',1,0,0,0,['death'])]
            self.doping=['stealth','death']
            self.catchphrase=(name+' senses murderous aura.',name+' senses murderous aura.')
        elif(num==3):
            self.leader=10
            self.hp=30
            self.str=24
            self.dex=30
            self.int=12
            self.AC=12
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=14
            self.shout=1
            self.icon=Boss_icon
            self.name='Kill-Shot'
            self.inventory=[]
            self.wear=Armor(1,Armor_icon,'robe',0)
            self.wield=Weapon(6,6,2,Weapon_icon,'Shinzowatari',3,6,2,4,['purify'])
            self.DV=1
            self.shield=self.wield
            self.ER=self.wear.ER+self.shield.ER
            self.MR=self.shield.MR+2
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=1000000
            self.drop=[Weapon(6,6,2,Weapon_icon,'Shinzowatari',3,6,2,4,['purify'])]
            self.doping=['purify','kai','vampirism']
            self.catchphrase=(name+' senses '+name+"'s life force being drained.",name+' senses '+name+"'s life force being drained.")
        elif(num==4):
            self.leader=10
            self.hp=60
            self.str=30
            self.dex=30
            self.int=30
            self.AC=12
            self.bp=0
            self.fp=0
            self.aware=0
            self.type=4
            self.shout=1
            self.icon=Boss_icon
            self.name='Shounin Bat'
            self.inventory=[]
            self.wear=Armor(3,Armor_icon,'leather armor',2)
            self.wield=Weapon(4,4,2,Weapon_icon,'Silver Bat',1,0,0,0,['illusion'])
            self.DV=1
            self.shield=self.wield
            self.ER=self.wear.ER
            self.MR=4
            self.lvl=99
            self.mp=(self.int*self.wield.intm*ER_divide)//(ER_divide+self.ER)
            self.VIT=self.hp
            self.BAC=self.AC-self.wear.AC-self.shield.AC
            self.xp=5000000
            self.drop=[Weapon(4,4,2,Weapon_icon,'Silver Bat',1,0,0,0,['illusion'])]
            self.doping=['illusion','roller-skates','kai']
            self.catchphrase=(name+' shivers as '+name+' hears sound of inline skates.',name+' shivers as '+name+' hears sound of inline skates.')
